apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quinoa-wind-turbine
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quinoa-wind-turbine
    app.kubernetes.io/part-of: quinoa-wind-turbine
  name: quinoa-wind-turbine
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: quinoa-wind-turbine
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: quinoa-wind-turbine
    spec:
      containers:
      - env:
        - name: INFINISPAN_PASSWORD
          value: WAo1jmPv
        - name: QUARKUS_PROFILE
          value: openshift-cluster
        image: quay.io/redhat-user-workloads/nvinto-ocm-tenant/quinoa-wind-turbine/quinoa-wind-turbine@sha256:a00698a9b85be3d02dfa6ddebb3a2a91eb7a0b0f0922a5c9048b2670c11e5c64
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
